package com.angelalmuenda.dangerpredict;

import android.widget.Button;

public class PredictData {

    public Button buttonPredict;

    public String[] crime_labels = {
            "Carnapping (R.A. 6539)",
            "Drug Related Incident (RA 9165)",
            "Murder/Homicide",
            "Physical Injuries",
            "Rape (Art. 266-A RC & R.A.8353)",
            "Robbery",
            "Theft"
    };

    public String[] ind_vars = {
            "lng",
            "lat",
            "Temp (deg celsius)",
            "Feels Like (deg celsius)",
            "Wind (km/h)",
            "Cloud",
            "Humidity",
            "Precip (mm)",
            "Pressure (mb)",
            "Bank",
            "Bar",
            "Beach",
            "Bridge",
            "Cemetery",
            "Church",
            "Clinic",
            "Commercial Building",
            "Community Center",
            "Convenience Store",
            "Fire Station",
            "Gas Station",
            "Government Office",
            "Greenfield",
            "Highway",
            "Highway Pedestrian",
            "Highway Primary",
            "Highway Residential",
            "Highway Secondary",
            "Highway Tertiary",
            "Hospital",
            "Hotel",
            "Industrial Building",
            "Mall",
            "Marketplace",
            "Park",
            "Parking Area",
            "Pawnshop",
            "Pharmacy",
            "Police Station",
            "Post Office",
            "Private Office",
            "Recreational Area",
            "Residential Building",
            "Restaurant",
            "Road",
            "School",
            "Sports Center",
            "Tourist Attraction",
            "Transport Terminal",
            "php-usd-rate",
            "PSE-index-Close",
            "Education,Baccalauate graduate",
            "Education,College undergraduate",
            "Education,Elementary",
            "Education,High school",
            "Education,No grade completed",
            "Education,Out of school youth",
            "Education,Post baccalaureate",
            "Education,Postsecondary",
            "Household,number of households",
            "Household,total annual household expenditure",
            "Household,total annual household income",
            "Housing,dwelling tenure status,Own house rent lot",
            "Housing,dwelling tenure status,Own house rent,free lot with consent of owner",
            "Housing,dwelling tenure status,Own house rent,free lot without consent of owner",
            "Housing,dwelling tenure status,Own or owner,like possession of house and lot",
            "Housing,dwelling tenure status,Rent house/ room including lot",
            "Housing,dwelling tenure status,Rent,free house and lot with consent of owner",
            "Housing,dwelling tenure status,Rent,free house and lot without consent of owner",
            "Housing,occupied housing,Commercial/industrial/agricultural,household",
            "Housing,occupied housing,Commercial/industrial/agricultural,population",
            "Housing,occupied housing,Duplex,household",
            "Housing,occupied housing,Duplex,population",
            "Housing,occupied housing,Multiunit residential,household",
            "Housing,occupied housing,Multiunit residential,population",
            "Housing,occupied housing,Single house,household",
            "Housing,occupied housing,Single house,population",
            "Labor,Employed",
            "Labor,In the Labor Force",
            "Labor,Not in the Labor Force",
            "Labor,Underemployed",
            "Labor,Unemployed",
            "Marital Status,Common law/livein",
            "Marital Status,Divorced/Separated",
            "Marital Status,Married",
            "Marital Status,Single",
            "Marital Status,Widowed",
            "Population",
            "Population,00-01",
            "Population,01-04",
            "Population,05-09",
            "Population,10-14",
            "Population,15-19",
            "Population,20-24",
            "Population,25-29",
            "Population,30-34",
            "Population,35-39",
            "Population,40-44",
            "Population,45-49",
            "Population,50-54",
            "Population,55-59",
            "Population,60-64",
            "Population,65-69",
            "Population,70-74",
            "Population,75-79",
            "Population,80 years and over ",
            "Poverty,poverty incidence by employed",
            "Poverty,poverty incidence by household",
            "Poverty,poverty incidence by population",
            "Poverty,poverty incidence by unemployed",
            "Consumer Price Index  - all items",
            "Consumer Price Index -Alcoholic beverages and tobacco",
            "Consumer Price Index -transport",
            "Consumer Price Index -Housing, water, electricity, gas, and other fuels",
            "Consumer Price Index -Restaurant and miscellaneous goods and services",
            "inflation rate",
            "savings deposit interest rate",
            "bank lending rates",
            "time_epoch_After Midnight",
            "time_epoch_After Work-Hours",
            "time_epoch_Afternoon",
            "time_epoch_Early Morning",
            "time_epoch_Evening",
            "time_epoch_Morning",
            "day_Friday",
            "day_Monday",
            "day_Saturday",
            "day_Sunday",
            "day_Thursday",
            "day_Tuesday",
            "day_Wednesday",
            "Weather_Clear",
            "Weather_Cloudy",
            "Weather_Rainy",
            "day_night_daylight",
            "day_night_nighttime",
            "placetype_rural",
            "placetype_urban"
    };
}
